const T={en:{login:'Sign in',email:'Email',password:'Password',projects:'Projects',addProject:'New project',addTask:'New task',notStarted:'Not Started',inProgress:'In Progress',completed:'Completed',total:'Total',logout:'Log out',theme:'Theme',project:'Project',taskTitle:'Task title',description:'Description',priority:'Priority',due:'Due date',save:'Save',cancel:'Cancel',delete:'Delete',low:'Low',medium:'Medium',high:'High',welcome:'Your workspace',noProject:'Create a project to get started.',invalid:'Please check your credentials.'},ar:{login:'تسجيل الدخول',email:'البريد الإلكتروني',password:'كلمة المرور',projects:'المشاريع',addProject:'مشروع جديد',addTask:'مهمة جديدة',notStarted:'لم تبدأ',inProgress:'قيد التنفيذ',completed:'مكتملة',total:'الإجمالي',logout:'تسجيل الخروج',theme:'المظهر',project:'المشروع',taskTitle:'اسم المهمة',description:'الوصف',priority:'الأولوية',due:'تاريخ التسليم',save:'حفظ',cancel:'إلغاء',delete:'حذف',low:'منخفض',medium:'متوسط',high:'مرتفع',welcome:'مساحتك',noProject:'أنشئ مشروعًا للبدء.',invalid:'تحقق من بيانات الدخول.'},es:{login:'Iniciar sesión',email:'Correo electrónico',password:'Contraseña',projects:'Proyectos',addProject:'Nuevo proyecto',addTask:'Nueva tarea',notStarted:'No iniciada',inProgress:'En progreso',completed:'Completada',total:'Total',logout:'Cerrar sesión',theme:'Tema',project:'Proyecto',taskTitle:'Título de tarea',description:'Descripción',priority:'Prioridad',due:'Fecha límite',save:'Guardar',cancel:'Cancelar',delete:'Eliminar',low:'Baja',medium:'Media',high:'Alta',welcome:'Tu espacio',noProject:'Crea un proyecto para empezar.',invalid:'Comprueba tus credenciales.'}};
let lang=localStorage.getItem('mm_lang')||'en', theme=localStorage.getItem('mm_theme')||'dark', client=null, user=null, projects=[],tasks=[],selected=null;
const $=s=>document.querySelector(s); const tr=k=>T[lang][k]||k;
function init(){document.documentElement.dataset.theme=theme; if(window.SUPABASE_URL!=='YOUR_SUPABASE_URL'&&window.supabase){client=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY); client.auth.getSession().then(({data})=>{user=data.session?.user||null; render(); if(user)load()});}else render();}
async function load(){const p=await client.from('projects').select('*').order('created_at'); const t=await client.from('tasks').select('*').order('created_at'); projects=p.data||[];tasks=t.data||[];selected=selected&&projects.find(x=>x.id===selected)?selected:projects[0]?.id||null;render();}
function render(){if(!user){document.body.innerHTML=`<div class="auth"><form class="auth-card" id="login"><div class="brand">Mohamed Mohsen</div><div class="sub">${tr('welcome')}</div><div class="field"><label>${tr('email')}</label><input id="email" type="email" value="mohamedmohsen.webdeveloper@gmail.com" required></div><div class="field"><label>${tr('password')}</label><input id="password" type="password" required></div><button class="primary">${tr('login')}</button><div class="error" id="err"></div><div class="lang"><button type="button" onclick="setLang('en')">EN</button><button type="button" onclick="setLang('ar')">AR</button><button type="button" onclick="setLang('es')">ES</button></div></form></div>`;$('#login').onsubmit=login;return}document.body.innerHTML=`<div class="layout"><aside class="sidebar"><div class="logo">Mohamed Mohsen</div><div class="side-title">${tr('projects')}</div><button class="btn primary2" onclick="newProject()">+ ${tr('addProject')}</button><div class="project-list">${projects.map(p=>`<button class="project-btn ${p.id===selected?'active':''}" onclick="selectProject('${p.id}')">${esc(p.name)}</button>`).join('')||`<div class="empty">${tr('noProject')}</div>`}</div><div class="side-bottom"><button class="ghost" onclick="toggleTheme()">☾ / ☀ ${tr('theme')}</button><div class="lang"><button onclick="setLang('en')">EN</button><button onclick="setLang('ar')">AR</button><button onclick="setLang('es')">ES</button></div><button class="ghost danger" onclick="logout()">${tr('logout')}</button></div></aside><main>${main()}</main></div>`;}
function main(){const p=projects.find(x=>x.id===selected);if(!p)return `<div class="topbar"><div class="title"><h1>${tr('welcome')}</h1><p>${tr('noProject')}</p></div></div>`;const ts=tasks.filter(t=>t.project_id===p.id);return `<div class="topbar"><div class="title"><h1>${esc(p.name)}</h1><p>${esc(p.description||'')}</p></div><div class="actions"><button class="btn" onclick="editProject()">Edit</button><button class="btn danger" onclick="deleteProject()">${tr('delete')}</button><button class="btn primary2" onclick="newTask()">+ ${tr('addTask')}</button></div></div><div class="stats"><div class="stat"><span>${tr('total')}</span><strong>${ts.length}</strong></div><div class="stat"><span>${tr('notStarted')}</span><strong>${ts.filter(x=>x.status==='not_started').length}</strong></div><div class="stat"><span>${tr('inProgress')}</span><strong>${ts.filter(x=>x.status==='in_progress').length}</strong></div><div class="stat"><span>${tr('completed')}</span><strong>${ts.filter(x=>x.status==='completed').length}</strong></div></div><div class="board">${col('not_started',tr('notStarted'),ts)}${col('in_progress',tr('inProgress'),ts)}${col('completed',tr('completed'),ts)}</div>`}
function col(status,title,ts){const arr=ts.filter(t=>t.status===status);return `<section class="column"><div class="colhead"><b>${title}</b><span class="count">${arr.length}</span></div>${arr.map(taskCard).join('')||'<div class="empty">—</div>'}</section>`}
function taskCard(t){return `<article class="task"><h3>${esc(t.title)}</h3>${t.description?`<p>${esc(t.description)}</p>`:''}<div class="meta"><span class="pill">${tr(t.priority)}</span><span class="pill">${t.due_date||''}</span></div><div class="task-actions"><button class="icon" onclick="editTask('${t.id}')">✎</button><button class="icon danger" onclick="deleteTask('${t.id}')">×</button><select onchange="setStatus('${t.id}',this.value)"><option value="not_started" ${t.status==='not_started'?'selected':''}>${tr('notStarted')}</option><option value="in_progress" ${t.status==='in_progress'?'selected':''}>${tr('inProgress')}</option><option value="completed" ${t.status==='completed'?'selected':''}>${tr('completed')}</option></select></div></article>`}
async function login(e){e.preventDefault();if(!client){$('#err').textContent='Configure Supabase in config.js first.';return}const {data,error}=await client.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error){$('#err').textContent=error.message;return}user=data.user;await load()}
async function logout(){if(client)await client.auth.signOut();user=null;projects=[];tasks=[];render()}
async function newProject(){const name=prompt('Project name');if(!name||!client)return;await client.from('projects').insert({user_id:user.id,name});await load()}
async function editProject(){const p=projects.find(x=>x.id===selected);const name=prompt('Project name',p.name);if(name)await client.from('projects').update({name}).eq('id',p.id);await load()}
async function deleteProject(){if(!confirm('Delete this project and its tasks?'))return;await client.from('projects').delete().eq('id',selected);selected=null;await load()}
async function newTask(){const title=prompt('Task title');if(!title)return;await client.from('tasks').insert({user_id:user.id,project_id:selected,title});await load()}
async function editTask(id){const t=tasks.find(x=>x.id===id);const title=prompt('Task title',t.title);if(title)await client.from('tasks').update({title,updated_at:new Date().toISOString()}).eq('id',id);await load()}
async function deleteTask(id){if(!confirm('Delete this task?'))return;await client.from('tasks').delete().eq('id',id);await load()}
async function setStatus(id,status){await client.from('tasks').update({status,updated_at:new Date().toISOString()}).eq('id',id);await load()}
function selectProject(id){selected=id;render()}
function toggleTheme(){theme=theme==='dark'?'light':'dark';localStorage.setItem('mm_theme',theme);document.documentElement.dataset.theme=theme;render()}
function setLang(l){lang=l;localStorage.setItem('mm_lang',l);render()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();
